/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }


    public static boolean hasAllThree(ArrayList<Integer> array, Integer a, Integer b, Integer c) {
        
        if (array == null) {
            return false;
        }

        boolean hasA = false, hasB = false, hasC = false;
        for (int i : array) {
            if (i == a) {
                hasA = true;
            }
            if (i == b) {
                hasB = true;
            }
            if (i == c) {
                hasC = true;
            }
        }

        if (hasA && hasB && hasC) {
            return true;
        }
        else {
            return false;
        }
    }


}
