/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import spark.ModelAndView;
import spark.template.mustache.MustacheTemplateEngine;
import static spark.Spark.get;
import static spark.Spark.post;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        get("/", (req, res) -> "Hello, World!!!");

        get("/compute",
            (rq, rs) -> {
                Map<String, String> map = new HashMap<String, String>();
                map.put("result", "not computed yet!");
                return new ModelAndView(map, "compute.mustache");
            },
            new MustacheTemplateEngine()
        );

        post("/compute", (req, res) -> {
            String input1 = req.queryParams("input1");
            java.util.Scanner sc1 = new java.util.Scanner(input1);
            sc1.useDelimiter("[;\r\n]+");
            java.util.ArrayList<Integer> inputList = new java.util.ArrayList<>();
            while (sc1.hasNext())
            {
                int value = Integer.parseInt(sc1.next().replaceAll("\\s",""));
                inputList.add(value);
            }
            sc1.close();
            System.out.println(inputList);


            String input2 = req.queryParams("input2").replaceAll("\\s","");
            int input2asInt = Integer.parseInt(input2);

            String input3 = req.queryParams("input3").replaceAll("\\s","");
            int input3asInt = Integer.parseInt(input3);

            String input4 = req.queryParams("input4").replaceAll("\\s","");
            int input4asInt = Integer.parseInt(input4);



            boolean result = App.hasAllThree(inputList, input2asInt, input3asInt, input4asInt);

            Map<String, Boolean> map = new HashMap<String, Boolean>();
            map.put("result", result);
            return new ModelAndView(map, "compute.mustache");
        }, new MustacheTemplateEngine());

    }


    public static boolean hasAllThree(ArrayList<Integer> array, Integer a, Integer b, Integer c) {
        
        if (array == null) {
            return false;
        }

        boolean hasA = false, hasB = false, hasC = false;
        for (int i : array) {
            if (i == a) {
                hasA = true;
            }
            if (i == b) {
                hasB = true;
            }
            if (i == c) {
                hasC = true;
            }
        }

        if (hasA && hasB && hasC) {
            return true;
        }
        else {
            return false;
        }
    }


}
