/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw;

import org.junit.jupiter.api.Test;

import jdk.jfr.Timestamp;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testHasAllThree() {
        ArrayList<Integer> array = new ArrayList<>();
        array.add(1);array.add(2);array.add(5);array.add(3);array.add(4);
        assertTrue(App.hasAllThree(array, 1, 2, 3));
    }

    @Test
    public void testHasFirstButNotTheOtherTwo() {
        ArrayList<Integer> array = new ArrayList<>();
        array.add(1);array.add(7);array.add(5);array.add(9);array.add(4);
        assertFalse(App.hasAllThree(array, 1, 2, 3));
    }

    @Test
    public void testHasFirstTwoButNotTheOtherOne() {
        ArrayList<Integer> array = new ArrayList<>();
        array.add(1);array.add(7);array.add(2);array.add(9);array.add(4);
        assertFalse(App.hasAllThree(array, 1, 2, 3));
    }

    @Test
    public void testEmptyArray() {
        ArrayList<Integer> array = new ArrayList<>();
        assertFalse(App.hasAllThree(array, 1, 2, 3));
    }

    @Test
    public void testNullArray() {
        assertFalse(App.hasAllThree(null, 1, 2, 3));
    }
    
    
}
